# C?u h�nh k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ql_ky_tuc_xa
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true